name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run Rust tests
        run: cargo test --verbose
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: PyO3/maturin-action@v1
        with:
          command: develop
          args: --release
      - name: Install Python dependencies
        run: |
          pip install uv
          uv pip install -e .
      - name: Run Python tests
        run: pytest -q
